name: 'Conditional value for GitHub Action'
description: 'Conditional value for GitHub Action - missing expression for GitHub Actions'
author: 'haya14busa'
inputs:
  cond:
    description: 'condition. [true,false]'
    required: true
  if_true:
    description: 'output value if cond is true'
    required: true
  if_false:
    description: 'output value if cond is false'
    required: true
outputs:
  value:
    description: 'output value'
runs:
  using: 'node12'
  main: 'dist/index.js'

# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: 'help-circle'
  color: 'white'
